# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a599ea7e358b254346fc929ca5112ca4b68e6f7af5bd80928c5b05b6c7ef60938f4cba557eab849c244ed53749ab1b73b78d66010826b83b4474e0c750eb4ae8

test:
  secret_key_base: dbe29d96606da02c3122e5d52b0f4cff5cc6535b2c1a403d4d52cd1228de5b87d2829bc08b4756e55b6b2b308ac87eb75f0e78ac6029eb0631b407ead1101ba1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
